spring:
  datasource:
    url: jdbc:mysql://localhost/emsdb?createDatabaseIfNotExists=true
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    cors:
      allowed-origins:
        - http://localhost:4200
  jpa:
    hibernate:
      ddl-auto: update

