spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system?createDatabaseIfNotExists=true
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
